services:
  vue:
    build:
      context: client
    depends_on: 
      django:
        condition: service_healthy
    container_name: xrb-vue
    ports:
      - "8080:8080"

  django:
    build:
      context: server
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      start_period: 30s
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api"]
    container_name: xrb-django
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres:
    env_file:
      - .env
    healthcheck:
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h localhost -p $POSTGRES_PORT"]
    image: postgres:15-alpine
    container_name: xrb-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: