services:
  nginx:
    build:
      context: client
      network: host
    container_name: xrb-nginx
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xrb-network
    ports:
      - "8080:8080"
    
  django:
    build:
      context: server
      network: host
    container_name: xrb-django
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - xrb-network
    volumes:
      - ./docker-data/data:/data

  postgres:
    container_name: xrb-postgres
    env_file:
      - .env
    healthcheck:
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h localhost -p $POSTGRES_PORT"]
    image: postgres:15-alpine
    networks:
      - xrb-network
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    
networks:
  xrb-network:
    driver: bridge
