services:
  nginx:
    build:
      context: client
    container_name: xrb-nginx
    ports:
      - "8080:8080"
    networks:
      - xrb_network

  django:
    build:
      context: server
    depends_on:
      postgres:
        condition: service_healthy
    container_name: xrb-django
    env_file:
      - .env
    hostname: django
    ports:
      - "8000:8000"
      - "10021:10021" # 10021 is used as port for FTP server since 21 requires root access
    networks:
      - xrb_network

  postgres:
    env_file:
      - .env
    healthcheck:
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h localhost -p $POSTGRES_PORT"]
    image: postgres:15-alpine
    container_name: xrb-postgres
    ports:
      - "5432:5432"
    networks:
      - xrb_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
networks:
  xrb_network:
    driver: bridge

volumes:
  postgres_data:
