services:
  nginx:
    build:
      context: client
      network: host
    depends_on:
      postgres:
        condition: service_healthy
    container_name: xrb-nginx
    ports:
      - "8080:8080"
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  django:
    build:
      context: server
      network: host
    depends_on:
      postgres:
        condition: service_healthy
    container_name: xrb-django
    env_file:
      - .env
    network_mode: "service:nginx"

  postgres:
    env_file:
      - .env
    healthcheck:
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h localhost -p $POSTGRES_PORT"]
    image: postgres:15-alpine
    container_name: xrb-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
